### ISSUE TITLE
Set up an AWS admin user for Sierra

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/etygraph-issues#1]
I want an AWS admin user in my account for [SierraS](https://github.com/sierras) that has full admin access, with access then revoked for anything related to [Very Awesome Passover/Mad Liberation](https://www.veryawesomepassover.com).

It needs to be in my AWS account so that she can use my Business-level support plan.

Acceptance criteria:
- [x] An admin_sierra user exists in my AWS account
- [ ] Policies are in place giving admin_sierra full admin access, with access revoked on Mad Liberation resources
  - [x] DNS hosted zones
  - [x] SSL certs
  - [x] S3 buckets
  - [x] CloudFormation stacks
  - [x] Lambdas
  - [x] API Gateway APIs
  - [x] DB(s)
  - [x] CodeStar projects
  - [x] Pipelines
  - [ ] CodeDeploy
  - [ ] CodeBuild
  - [ ] Cloud9
  - [ ] CloudFront distributions
  - [ ] CloudWatch
  - [ ] CloudTrail
  - [ ] EC2 instances
  - [ ] IAM (prevent admin_sierra from changing her own permissions, probably need to remove the IAM grant all from the admin group and add a more restrictive version, but maybe can override with denies, might need a new "restricted_admin group," will need verification steps)
- [ ] Verification: have admin_sierra try to make harmless modifications on some of the above resources, or on non-Mad-Liberation resources with access revoked in an identical fashion.
- [ ] Verification: have admin_sierra create a CodeStar project for Etygraph
- [ ] admin_sierra is listed with the right to raise support issues
- [ ] Verification: have admin_sierra raise a support issue, maybe even just one asking to confirm whether permissions are set up correctly
- [ ] Group Deny..-MadLiberation policies together

**Comment by douglasnaphas** [comment]
# Resources
https://serverfault.com/questions/364264/how-do-i-determine-the-arn-of-my-amazon-route53-hosted-zone
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/auth-and-access-control.html

**Comment by douglasnaphas** [comment]
# Sub-task: script to join statements from policies matching a name pattern to one body
[douglasnaphas/aws-scripts](https://github.com/douglasnaphas/aws-scripts) is set up for this.
- [ ] Publish aws-scripts via npm.
- [ ] Make a [Commander](https://github.com/tj/commander.js) sub-command `join-statements`. I can't have more than 10 policies attached to a user, so I need to join my Denies into one.
